version: "3"
services:
  mongo:
    image: mongo
    build:
      context: .
      dockerfile: mongo/Dockerfile
    ports:
      - "27017:27017"
  nodejs:
    image: oolo/wildcards-api:latest
    build:
      context: .
      dockerfile: nodejs/Dockerfile
    environment:
      - NODE_ENV=docker
    links:
      - mongo
    ports:
      - "80:8443"
    command: npm start
  php:
    image: oolo/wildcards-cms:latest
    build:
      context: .
      dockerfile: php/Dockerfile
    links:
      - mongo
    ports:
      - "81:80"
